[package]
## should be named crabby by following workshop
## different name because used as workspace member to check all projects easily
name = "crabby_args"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
